version: 2.0

machine:
  environment:
    COVERALLS_REPO_TOKEN: rIJkRSS9UwX1JtWZOKlAP5EH4WCxogDSu
    COVERALLS_PARALLEL: true

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=<<YOUR TOKEN>>

jobs:
    build:
        docker:
            - image: circleci/openjdk:9-jdk-sid-node-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: gradle assemble
            - run: gradle test
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
